{
    'name': 'FMS',
    'version': '1.0',
    'category': 'Services',
    'summary': 'Facility Management System',
    'author': 'Your Company',
    'website': 'https://www.yourcompany.com',
    'license': 'LGPL-3',
    'depends': ['base', 'sale', 'purchase', 'account', 'web', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'data/fms_sequence.xml',
        'data/job_name.xml',
        'views/fms_service_category_views.xml',
        'views/fms_site_views.xml',
        'views/fms_rate_card_views.xml',
        'views/fms_vendor_rate_card_views.xml',
        'views/hr_employee_views.xml',
        'views/fms_ticket_views.xml',
        'views/fms_job_views.xml',
        'views/res_partner_views.xml',
        'views/fms_ticket_sla_view.xml',
        'views/fms_sla_rule_views.xml',
        'views/fms_scope_approval_views.xml',
        'views/fms_consolidated_invoice_views.xml',
        'wizard/consolidated_billing_wizard_views.xml',
        'views/sale_order_views.xml',
        'views/fms_sla_report_views.xml',
        'views/fms_portal_template.xml',
        'views/fms_menu.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'sequence': 10,
    'price': 499.00,
    'currency': 'USD',
    'support': 'support@yourcompany.com',
}
